### ISSUE TITLE
Signals not working properly

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#20]
Signal ctrl+c doesn't display shell prompt automatically, you've got to press enter.

**Comment by Dymirt** [comment]
Works on my machine 🥲

**Comment by hipoliciak** [comment]
Input: ctrl+\ (3 times), ctrl+C (a few times), ctrl+D.

Our program:
![Zrzut ekranu 2024-08-31 133120](https://github.com/user-attachments/assets/4803a941-0b63-4799-b50b-f2177c067c03)
Another minishell I found online:
![Zrzut ekranu 2024-08-31 133245](https://github.com/user-attachments/assets/4b9c5c21-29b7-4378-a860-9b35c7dba7f2)
Bash:
![Zrzut ekranu 2024-08-31 133439](https://github.com/user-attachments/assets/2222dda3-8bab-4283-b39c-8fd407a4af37)

**Comment by Dymirt** [comment]
is that a really an issue? Does this behaviour is required?

**Comment by hipoliciak** [comment]
Unfortunately, this is how it is described in the project description :(

Handle ctrl-C, ctrl-D and ctrl-\ which should behave like in bash.
In interactive mode:
◦ ctrl-C displays a new prompt on a new line.
◦ ctrl-D exits the shell.
◦ ctrl-\ does nothing.

**Comment by hipoliciak** [comment]
Fixed on branch builtin_fixes
