### ISSUE TITLE
env path check

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#23]
We need to make sure it works as in eval sheet:

- [X] Execute commands but this time use a relative path.
- [X] Repeat multiple times in different directories with a complex relative path (lots of ..).
- [X] Execute commands but this time without any path (ls, wc, awk and so forth).
- [ ] Unset the $PATH and ensure commands are not working anymore.
- [ ] Set the $PATH to a multiple directory value (directory1:directory2) and ensure that directories are checked in order from left to right.

**Comment by Dymirt** [comment]
is that's looks right?
`minishell> $ /bin/ls
LICENSE
Makefile
README.md
get_next_line
includes
libft
minishell
minishell_tester
objs
srcs
venv`

**Comment by Dymirt** [comment]
is that's looks right?
`minishell> $ /bin/ls
LICENSE
Makefile
README.md
get_next_line
includes
libft
minishell
minishell_tester
objs
srcs
venv`

**Comment by hipoliciak** [comment]
I created a separate issue specifically for unsetting the PATH: https://github.com/hipoliciak/minishell/issues/35
