### ISSUE TITLE
Handling several redirections

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#26]
Our minishell doesn't properly handle several redirections one after another. From what I understand, the program should execute them one by one and if there is an error - return the last exit code and error.
 
First example - program should stop when trying to execute the first redirection (wrong permission):
ls >>./test_files/invalid_permission >>./outfiles/outfile02 <missing
mini output = (./test_files/invalid_permission)
bash output = ()
mini exit code = 0
bash exit code = 1
mini error = ( No such file or directory)
bash error = ( Permission denied)

Second example - program should stop when trying to execute the last redirection:
echo hi | echo >>./outfiles/outfile01 bye >./test_files/invalid_permission
Only in ./bash_outfiles: outfile01
mini outfiles:
cat: './mini_outfiles/*': No such file or directory
bash outfiles:
mini output = (hi)
bash output = ()
mini exit code = 0
bash exit code = 1
mini error = ()
bash error = ( Permission denied)

**Comment by Dymirt** [comment]
- [ ] Handle >> redirection
- [ ] Handle multiple export > redirections in one group
