### ISSUE TITLE
Creating files with redirections

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#27]
Our redirections don't create files. It seems we're only reading from / adding to existing files.

ls >>./outfiles/outfile01 >>./outfiles/outfile02
Only in ./bash_outfiles: outfile01
Only in ./bash_outfiles: outfile02
mini outfiles:
cat: './mini_outfiles/*': No such file or directory
bash outfiles:
12345
456
>
README.md
bash.supp
bash_outfiles
bonus
bonus_bonus
builtins
extras
local.supp
loop.out
manual_tests
mini_outfiles
missing
os_specific
outfiles
pipes
redirects
syntax
test_files
tester
wildcards
mini error = ( No such file or directory No such file or directory)
bash error = ()

**Comment by Dymirt** [comment]
This issue is described in #26
