### ISSUE TITLE
Output handling in pipes

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#28]
Command export GHOST=123 | env | grep GHOST prints GHOST=123 in our shell and results in 0 exit code. In bash it doesn't print anything and results in 1 exit code.

The reason for that is that export GHOST=123 command doesn't produce any output to the standard output (stdout); it only sets the environment variable. Since there's no output from export, the pipe (|) passes an empty input to the env | grep GHOST command, and thus nothing is printed.

Our pipes should check the output and use it only if it's valid to be passed with pipe.

**Comment by Dymirt** [comment]
`dmytrokolida@Dmytros-MacBook % export GHOST=123 | env | grep GHOST`
`dmytrokolida@Dmytros-MacBook % env`
no GHOST in env.....
`dmytrokolida@Dmytros-MacBook % export GHOST=123    `               
`dmytrokolida@Dmytros-MacBook % env`
`GHOST=123`
now GHOST is there

And when you run the this command again
`dmytrokolida@Dmytros-MacBook % export GHOST=1234 | env | grep GHOST`
`GHOST=123`

`dmytrokolida@Dmytros-MacBook % env`
`GHOST=123`
GHOST remains the same as before with no changes...

conclusion: In original zsh export not working with pipes....

> The reason for that is that export GHOST=123 command doesn't produce any output to the standard output (stdout); it only sets the environment variable. Since there's no output from export, the pipe (|) passes an empty input to the env | grep GHOST command, and thus nothing is printed.

True that export GHOST=123 command doesn't produce any output to the standard output (stdout), but it's not a case why is nothing is printed in terminal.

In my opinion its not and issue, its rather a feature that works better then in original terminal.

**Comment by hipoliciak** [comment]
I can't agree. This command: export GHOST=123 | env | grep GHOST should result in an exit with status 1. This is how it is handled in bash and zsh. This is how pipes work - first command results in no output, so the second and third don't have anything to work with.

export GHOST=123 | env | grep GHOST
is not the same as
export GHOST=123
env | grep GHOST

![image](https://github.com/user-attachments/assets/f16a741a-a618-4caf-8422-cb94bba982ef)

**Comment by hipoliciak** [comment]
I think this is also highlighted in this part of project description:

Implement pipes (| character). The output of each command in the pipeline is
connected to the input of the next command via a pipe

**Comment by Dymirt** [comment]
> The output of each command in the pipeline is
connected to the input of the next command via a pipe

that's how our pipes works.

I think that you should test it with other inputs than 123.... Try to run in original terminal
` export GHOST=12345 | env | grep GHOST`
then
`env `
and see if you will change GHOST in to new value....
