### ISSUE TITLE
Improper code when command not found

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#29]
Using a non existing command doesn't update the exit code. It's still 0. Comparison with bash below:

![image](https://github.com/user-attachments/assets/66210aed-1a97-44e8-8d68-365ca406e558)

- [ ] Add command validation check in shell_exec

**Comment by Dymirt** [comment]
I think that this issue is because of fork(), all commands is executed in child process, except buildins. I think we can try to check if the command is existing before passing it to child. some thing like iteration thru path and checking the access...

**Comment by hipoliciak** [comment]
I've done some tests and I believe the problem is exactly where you wrote. Exit status is not passed to the parent process :/
And yeah, it might be a good idea to check if the command is valid before trying to execute it.

**Comment by hipoliciak** [comment]
This needs to be fixed before evaluation. It's described in detail in the evaluation sheet:
![image](https://github.com/user-attachments/assets/7d660afe-3757-4d18-9e5f-fc662a25534b)
