### ISSUE TITLE
Echo '>' and ">" display empty line

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#33]
It's also one of the things that will be tested.
Result:
![image](https://github.com/user-attachments/assets/775e297e-b473-411d-8e33-9c7c2c435ff0)
Part of eval sheet:
![image](https://github.com/user-attachments/assets/62d0737e-41c0-45d9-b07e-f88f4d75dc74)

- [X] handle '>'
- [X] handle '<'
- [x] handle ">"
- [x] handle "<"

**Comment by hipoliciak** [comment]
In the current version echo ">" and echo '>' result in segfault :(

**Comment by hipoliciak** [comment]
'>', ">", '<', "<" - without anything else in the terminal - result in infinite loop. Process needs to be manually stopped, e.g. with ctrl+Z.

**Comment by Dymirt** [comment]
Ok, im working on this one now.

**Comment by Dymirt** [comment]
- [X] handle '>'
- [X] handle '<'
- [ ] handle '<<'
- [ ] handle '>>'

**Comment by hipoliciak** [comment]
Redirection in double quotes results in an empty line
![image](https://github.com/user-attachments/assets/066ebf6c-f46b-4c2e-9714-a3acb44b2a76)
