### ISSUE TITLE
Commands working even with PATH unset

### ISSUE THREAD

**Issue by hipoliciak** [hipoliciak/minishell#35]
Our commands shouldn't work without PATH in the environment but they are working :/

![image](https://github.com/user-attachments/assets/e0ed79c3-f1cd-43a2-bc68-44912e0cccdf)
![image](https://github.com/user-attachments/assets/15dd378a-4b3a-43e6-ab5c-6be0b4b60417)

- [ ] check if command unset $path is working properly ( run unset $path then env)

**Comment by Dymirt** [comment]
that's because unset probably is not working...
